### ISSUE TITLE
Make sorting by multiple columns optional.

### ISSUE THREAD

**Issue by limonte** [simplicitylabs/si-table#18]
In most cases when list is small (several pages) there's no need to use multiple columns sorting and this option can be unclear because user need to disable sorting by current column and only after this he can be available to sort by new column.

@mikberg WDYT about introducing option for sorting by multiple columns? I think default that option should be `false`. And developer can set it to true when he works with big lists like this:

    <tr si-sortable multiple-columns ng-repeat="user in users">

**Comment by mikberg** [comment]
I agree, in many cases there's no need for multiple-column sorting, but I'd prefer opt-out rather than opt-in so that we don't introduce a breaking change. What about something like this?

```html
<tr si-sortable="single" ng-repeat="user in users">
```

**Comment by limonte** [comment]
@mikberg looks good to me, I'll try to implement your suggestion
