### ISSUE TITLE
Error: [$parse:syntax] Syntax Error

### ISSUE THREAD

**Issue by agrigory1982** [simplicitylabs/si-table#22]
Seems like there is an Error with the directive. Maybe it is in Angular 1.4+

The Error:
Error: [$parse:ueoe] Unexpected end of expression: $parent.currentList = (postsList
http://errors.angularjs.org/1.4.1/$parse/ueoe?p0=%24parent.currentList%20%3D%20(postsList
    at http://localhost:9000/bower_components/angular/angular.js:68:12
    at Object.AST.consume (http://localhost:9000/bower_components/angular/angular.js:12872:13)
    at Object.AST.primary (http://localhost:9000/bower_components/angular/angular.js:12756:12)
    at Object.AST.unary (http://localhost:9000/bower_components/angular/angular.js:12748:19)
    at Object.AST.multiplicative (http://localhost:9000/bower_components/angular/angular.js:12735:21)
    at Object.AST.additive (http://localhost:9000/bower_components/angular/angular.js:12726:21)
    at Object.AST.relational (http://localhost:9000/bower_components/angular/angular.js:12717:21)
    at Object.AST.equality (http://localhost:9000/bower_components/angular/angular.js:12708:21)
    at Object.AST.logicalAND (http://localhost:9000/bower_components/angular/angular.js:12700:21)
    at Object.AST.logicalOR (http://localhost:9000/bower_components/angular/angular.js:12692:21) 

My table:
<table si-table class="table no-margin">
        <thead>
        <tr>
          <th>№</th>
          <th>Author Name</th>
          <th>Start</th>
          <th>End</th>
          <th sort-by="post.postState">State</th>
        </tr>
        </thead>
        <tbody>
        <tr si-sortable ng-repeat="post in postsList">
          <td>{{ $index+1 }}</td>
          <td>{{ post.author[0].name }}</td>
          <td>{{ post.schedulingStartDate | date:'yyyy-MM-dd' }}</td>
          <td>{{ post.schedulingEndDate | date:'yyyy-MM-dd' }}</td>
          <td>{{ post.postState }}</td>
          <td>
            <a href=""
               title="Approve post"
               ng-show="post.postState === 'need-approve'"
               ng-click="approvePost(post)">&#x2714;
            </a>
          </td>
          <td><a href="" title="Delete post" ng-click="deletePost(post)">&times;</a></td>
          
        </tr>
        </tbody>
        <tfoot>
        <tr>
          <td colspan="5">
            <si-table-pagination limit="10" indices="3"/>
          </td>
        </tr>
        </tfoot>
      </table>

**Comment by agrigory1982** [comment]
Please, help me out with this issue. I like a lot you directive!

**Comment by mikberg** [comment]
What's your expression in the ng-repeat attribute?

**Comment by agrigory1982** [comment]
<tr si-sortable ng-repeat="post in postsList"> - directive

controller:

    // Show Posts immediately when view activated
    var currentUser = Auth.getCurrentUser();
    $scope.postsList = {};
    $http.get('/api/posts', { params: { companyId: currentUser.companyId[0] } } ).success(function (posts) {
      $scope.postsList = posts;
      socket.syncUpdates('post', $scope.postsList);
    });

**Comment by limonte** [comment]
@agrigory1982 just fixed this issue, will push fix ASAP, cc @mikberg

**Comment by limonte** [comment]
@mikberg my PR will hotfix error from this issue, but selectAll directive won't work as documented: `currectList` will contain all items, not only filtered. Looking forward to resolve this.

**Comment by mikberg** [comment]
Cool, released version `0.2.1` with this fix now. Thanks, @limonte!

@agrigory1982 Did this solve your problem?

**Comment by agrigory1982** [comment]
Hello! Works now without this error, however, still sorting does not work...

**Comment by limonte** [comment]
@agrigory1982 can you please make a plunker that shows this?

**Comment by agrigory1982** [comment]
I've made this plunk: http://plnkr.co/edit/vAAocY4E1V6AgqEN8u2k?p=preview

**Comment by limonte** [comment]
Instead of

```html
<th sort-by="post.author">Author Name</th>
<th sort-by="post.postState">State</th>
```

you should use
```html
<th sort-by="author">Author Name</th>
<th sort-by="postState">State</th>
```

**Comment by agrigory1982** [comment]
Oh, Ive got it. Actually, I also noticed that if I have {{ post.rewardId[0].rewardName }}

I need to use sort-by="rewardId[0].rewardName"

this works, thank you for help!

**Comment by limonte** [comment]
@agrigory1982 you're welcome!

**Comment by mikberg** [comment]
:+1:
