### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: aProvider <- a <- sortByDirective

### ISSUE THREAD

**Issue by agrigory1982** [simplicitylabs/si-table#24]
Hello, guys!
I tested the directive in Dev mode, it works just fine, however when I put it into Production, I'm getting the following error:
Error: [$injector:unpr] Unknown provider: aProvider <- a <- sortByDirective
http://errors.angularjs.org/1.4.1/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-%20sortByDirective
    at 0a7f7d53.vendor.js:3
    at 0a7f7d53.vendor.js:4
    at Object.d [as get] (0a7f7d53.vendor.js:4)
    at 0a7f7d53.vendor.js:4
    at d (0a7f7d53.vendor.js:4)
    at Object.e [as invoke] (0a7f7d53.vendor.js:4)
    at 0a7f7d53.vendor.js:4
    at f (0a7f7d53.vendor.js:3)
    at Object.<anonymous> (0a7f7d53.vendor.js:4)
    at Object.e [as invoke] (0a7f7d53.vendor.js:4)

Don't know if it is a mess from minification, but have this problem only with sortByDirective. Everything else works well, including some other 3rd party modules.

And, yes, for Production and Development I'm using Angular-fullstack yeoman generator

**Comment by agrigory1982** [comment]
Temporaly, removed all-si-table directives - works without erroes. Any ideas why it is causing this error in Prod?

**Comment by limonte** [comment]
@agrigory1982 thank you for bug-report! It should be fixed with https://github.com/simplicitylabs/si-table/pull/25 after @mikberg merge it and bump patch version.

**Comment by agrigory1982** [comment]
@limonte thank you for quick help!
@mikberg please, merge asap. Can't wait to put it into Prod :)
