### ISSUE TITLE
remote pagination not working

### ISSUE THREAD

**Issue by fbkopp** [simplicitylabs/si-table#26]
Hi,

in the code below from si-table.js
```
scope.$watchCollection(collection, function() {
     scope.paginationParams.offset = 0;
});
```
 
will set always to first page in the pagination.

followed the example from http://simplicitylabs.github.io/si-table/remote.html
used si-table.js from last version from github

**Comment by limonte** [comment]
what's your question?

**Comment by ozexpert** [comment]
I found what the problem is...
Let say i have 1, 2, 3 pagination links.

If i click 2, it resets to 1 always because of the code @fbkopp mentioned.
So, it always resets to 0 offset. broken...

**Comment by ozexpert** [comment]
why do you have that line to reset offset to 0?? 
if i remove that code, everything works well...
