### ISSUE TITLE
sorting multiple columns

### ISSUE THREAD

**Issue by sbagchi** [simplicitylabs/si-table#6]
Does the si-table support sort-by option on multiple columns? 
When I added sort-by to two columns, sort on one column, then try to click the other column header, it doesn't sort on the second column. I have to bring back the first column sorting to neutral state before I can sort on the second column.
Is it possible to specify an option where sorting on one column automatically removes any existing sort order and resorts the data?

**Comment by kerbios** [comment]
250 line: 
// Tri-state: ascending -> descending -> neutral, represented by
        // an array as per Angular's orderBy specification.
        if (params.sortArray.indexOf(sortBy) !== -1) {
          // ascending -> descending
          params.sortArray = [sortBy];  //<== added
          params.sortArray[params.sortArray.indexOf(sortBy)] = '-' +
            sortBy;
          scope.state = 'desc';
        } else if (params.sortArray.indexOf('-' + sortBy) !== -1) {
          // descending -> neutral
          params.sortArray = ['-' + sortBy];  //<== added
          params.sortArray.splice(params.sortArray.indexOf('-' +
            sortBy), 1);
          scope.state = '';
        } else {
          // neutral -> ascending
          //
          params.sortArray = [];  //<==added
          params.sortArray.push(sortBy);
          scope.state = 'asc';
        }

This will fix the problem

**Comment by mikberg** [comment]
@kerbios Thanks! Could you submit a pull request?
